apiVersion: v1
kind: Service
metadata:
  name: myfirstloadbalancerservice # The name of the Service. It gets a DNS entry in the K8s own DNS 
  labels:
    name: myfirstloadbalancerservice
    env: local
spec:
  type: LoadBalancer
  selector: 
      tier: frontendwebserver
  ports:
    - name: http
      port: 8080 #this is going to be an external port being created
      targetPort: 80 #this is the container port