# Not able to understand why both containers are not running
# finally able to understand - it is due to port blocking ... chnaged the 2 nd conatiner port from 80range to 5000
apiVersion: v1
kind: Pod
metadata:
  name: nginxfromyaml # this is the name of the pod
  labels: 
    name: nginxweb
    env: local
spec:
  containers:
  - name: nginxfromyaml2 # this name of the container
    image: nginx:alpine
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    volumeMounts:
      - mountPath: /usr/share/nginx/html/abc/def # This is the path inside conatiner where the voule defined will be mounted. If not exists it will be created
        name: myemptydirvol

  - name: nginxfromyaml # this name of the container
    image: nginx:alpine
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
    volumeMounts:
      - mountPath: /usr/share/nginx/html/abc/yxz # # This is the path inside conatiner where the voule defined will be mounted. If not exists it will be created
        name: myemptydirvol

  volumes:
    - name: myemptydirvol
      emptyDir: {} # this default implementation creates the volume of the Nodes disk space. You could chnage it to RAM as well
        