apiVersion: apps/v1
kind: Deployment
metadata:
  name: podswithpvc # The name of the deployment
  labels:
    name: podswithpvc
    env: local
spec:
  replicas: 3
  selector: 
    matchLabels:
      tier: frontendwebserver
  template:
    metadata:
      labels:
        tier: frontendwebserver
    spec:
      containers:
      - name: mginxserver
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe: 
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 1   
        volumeMounts:
          - mountPath: /mnt/myvolume
            name: mypvcvolume
      volumes:
        - name: mypvcvolume
          persistentVolumeClaim:
            claimName: azurefile