apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi # This is should be same as PV storage Class Name
  #volumeName: azurefile (This is the binding reference to PV backing this claim)
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      roll: two
#(Also after creating the PVC check the STATUS of the PVC, if it is bound state means all are ok)
#(When Selector and VolumeName both are mentioned in the yaml to select from the avaibale Persistant volumes
# Then volumeName takes precidence 
# Else selector comes into play)
# PV to PVC mapping is One - to - One